# Generated by Django 4.1.7 on 2023-08-03 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_rename_oderitem_orderitem_product_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
    ]
